name: CI with Ceedling

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0'

    - name: Add Gem Directory to PATH
      run: echo "${HOME}/.local/share/gem/ruby/3.0.0/bin" >> $GITHUB_PATH

    - name: Install Ceedling
      run: gem install ceedling

    - name: Install Cppcheck
      run: sudo apt-get install -y cppcheck

    - name: Build and run tests with Ceedling for project_1
      working-directory: unit/test_project
      run: |
        ceedling test:all gcov:all

    - name: Build and run tests with Ceedling for project_2
      working-directory: Mock/blinky
      run: |
        ceedling test:all gcov:all

    - name: Build and run tests with Ceedling and Cppcheck
      working-directory: ceedling-cppcheck-example
      run: |
        ceedling test:all gcov:all cppcheck:all
