name: CI with Ceedling

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0'

    - name: Install Ceedling
      run: gem install ceedling && gem update ceedling 

    - name: Install Cppcheck
      run: sudo apt-get install -y cppcheck

    - name: Build and run tests with Ceedling for project_1
      working-directory: unit/test_project
      run: |
        ceedling test:all gcov:all

    - name: Build and run tests with Ceedling for project_2
      working-directory: Mock/blinky
      run: |
        ceedling test:all gcov:all

    # - name: Build and run tests with Ceedling and Cppcheck
    #   working-directory: ceedling-cppcheck-example/test_project
    #   run: |
    #     ceedling test:all gcov:all 
    - name: Run Cppcheck
      run: |
        ceedling cppcheck:all

      
        

